# Generated by Django 3.1.3 on 2022-04-16 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220416_1412'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='STATUS',
            new_name='status',
        ),
    ]
